### ISSUE TITLE
NEO and GAS balances not reflected on VisualTracker wallet view

### ISSUE THREAD

**Issue by zlewe** [neo-project/neo-blockchain-toolkit#20] opened 2021-04-21 04:16 UTC
![image](https://user-images.githubusercontent.com/2039692/115495528-69493200-a29a-11eb-8bc2-e6f590bd8db4.png)

Balances showed properly under NEP17 balances but not under NEO and GAS balances.

Toolkit version: 2.0.5
VS Code version: 1.55.2
OS: Ubuntu 20.04 LTS

**Comment by djnicholson** [comment] 2021-04-21 06:25
This is likely a duplicate of https://github.com/ngdenterprise/neo3-visual-tracker/issues/44

The fix is already merged and will be part of the next release (ETA: April 21)

**Closed** 2021-04-21 06:41 UTC
